#!/usr/bin/env bash
# Purpose: Installs the prek-managed git pre-commit hook in this repository.
# Usage:   install_precommit_hooks.sh
# Notes:   Delegates uv setup to install_uv.sh; installs prek if missing.
#          Refuses to overwrite a custom core.hooksPath.
set -euo pipefail
shopt -s inherit_errexit

die() { printf '%s\n' "$*" >&2; exit 1; }

confirm() {
  local prompt="$1"
  local response

  if [[ ! -t 0 ]]; then
    die "$prompt (no TTY available for confirmation; re-run interactively)"
  fi

  read -r -p "$prompt [y/N] " response
  [[ "$response" =~ ^[Yy]([Ee][Ss])?$ ]]
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
GIT_HOOKS_DIR="$(git -C "$PROJECT_ROOT" rev-parse --git-path hooks)"
PRE_COMMIT_HOOK="$GIT_HOOKS_DIR/pre-commit"
readonly SCRIPT_DIR PROJECT_ROOT GIT_HOOKS_DIR PRE_COMMIT_HOOK

# shellcheck source=install_uv.sh
source "$SCRIPT_DIR/install_uv.sh"

ensure_prek() {
  if command -v prek &> /dev/null; then
    return
  fi

  confirm "prek is not installed. Install it with 'uv tool install prek'?" \
    || die "prek is required; aborting"

  echo "Installing prek..."
  uv tool install prek
}

normalize_default_hooks_path() {
  local configured_hooks_path
  local resolved_hooks_path

  configured_hooks_path="$(git -C "$PROJECT_ROOT" config --local --get core.hooksPath || true)"
  if [[ -z "$configured_hooks_path" ]]; then
    return
  fi

  if [[ "$configured_hooks_path" == /* ]]; then
    resolved_hooks_path="$configured_hooks_path"
  else
    resolved_hooks_path="$(cd "$PROJECT_ROOT" && readlink -m "$configured_hooks_path")"
  fi

  if [[ "$resolved_hooks_path" == "$GIT_HOOKS_DIR" ]]; then
    confirm "Local core.hooksPath redundantly points at the default ($configured_hooks_path). Unset it?" \
      || die "Cannot proceed without unsetting core.hooksPath; aborting"
    git -C "$PROJECT_ROOT" config --unset-all --local core.hooksPath > /dev/null 2>&1 || true
    return
  fi

  die "core.hooksPath is set to a custom location ($configured_hooks_path); refusing to overwrite it."
}

main() {
  ensure_uv
  ensure_prek

  if [[ -f "$PRE_COMMIT_HOOK" ]] && grep -q "File generated by prek" "$PRE_COMMIT_HOOK"; then
    echo "prek hook already installed at $PRE_COMMIT_HOOK"
    return
  fi

  normalize_default_hooks_path

  if [[ -f "$PRE_COMMIT_HOOK" ]]; then
    confirm "An existing pre-commit hook at $PRE_COMMIT_HOOK will be overwritten. Continue?" \
      || die "Aborted; existing pre-commit hook left in place"
  else
    confirm "Install prek pre-commit hook at $PRE_COMMIT_HOOK?" \
      || die "Aborted; no hook installed"
  fi

  cd "$PROJECT_ROOT"
  prek install --overwrite
}

main "$@"
